-- Create test table for benchmarking
CREATE TABLE IF NOT EXISTS benchmark_data (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    age INTEGER NOT NULL,
    city VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_benchmark_email ON benchmark_data(email);
CREATE INDEX IF NOT EXISTS idx_benchmark_city ON benchmark_data(city);

-- Seed 100 records for realistic testing
INSERT INTO benchmark_data (name, email, age, city) VALUES
    ('Alice Johnson', 'alice.johnson@example.com', 28, 'New York'),
    ('Bob Smith', 'bob.smith@example.com', 35, 'Los Angeles'),
    ('Charlie Brown', 'charlie.brown@example.com', 42, 'Chicago'),
    ('Diana Prince', 'diana.prince@example.com', 31, 'Houston'),
    ('Edward Norton', 'edward.norton@example.com', 29, 'Phoenix'),
    ('Fiona Apple', 'fiona.apple@example.com', 38, 'Philadelphia'),
    ('George Miller', 'george.miller@example.com', 45, 'San Antonio'),
    ('Hannah Montana', 'hannah.montana@example.com', 26, 'San Diego'),
    ('Ian McKellen', 'ian.mckellen@example.com', 52, 'Dallas'),
    ('Julia Roberts', 'julia.roberts@example.com', 33, 'San Jose'),
    ('Kevin Hart', 'kevin.hart@example.com', 37, 'Austin'),
    ('Laura Palmer', 'laura.palmer@example.com', 24, 'Jacksonville'),
    ('Michael Scott', 'michael.scott@example.com', 41, 'Fort Worth'),
    ('Nancy Drew', 'nancy.drew@example.com', 27, 'Columbus'),
    ('Oscar Wilde', 'oscar.wilde@example.com', 46, 'Charlotte'),
    ('Patricia Hill', 'patricia.hill@example.com', 39, 'San Francisco'),
    ('Quincy Jones', 'quincy.jones@example.com', 55, 'Indianapolis'),
    ('Rachel Green', 'rachel.green@example.com', 30, 'Seattle'),
    ('Samuel Jackson', 'samuel.jackson@example.com', 48, 'Denver'),
    ('Tina Fey', 'tina.fey@example.com', 36, 'Washington'),
    ('Uma Thurman', 'uma.thurman@example.com', 43, 'Boston'),
    ('Victor Hugo', 'victor.hugo@example.com', 50, 'Nashville'),
    ('Wendy Williams', 'wendy.williams@example.com', 32, 'Baltimore'),
    ('Xavier Woods', 'xavier.woods@example.com', 29, 'Louisville'),
    ('Yolanda Adams', 'yolanda.adams@example.com', 44, 'Portland'),
    ('Zachary Levi', 'zachary.levi@example.com', 34, 'Las Vegas'),
    ('Amy Adams', 'amy.adams@example.com', 40, 'Milwaukee'),
    ('Brian Cox', 'brian.cox@example.com', 47, 'Albuquerque'),
    ('Catherine Zeta', 'catherine.zeta@example.com', 38, 'Tucson'),
    ('David Bowie', 'david.bowie@example.com', 51, 'Fresno'),
    ('Emma Stone', 'emma.stone@example.com', 28, 'Sacramento'),
    ('Frank Sinatra', 'frank.sinatra@example.com', 54, 'Mesa'),
    ('Grace Kelly', 'grace.kelly@example.com', 35, 'Kansas City'),
    ('Henry Cavill', 'henry.cavill@example.com', 33, 'Atlanta'),
    ('Iris West', 'iris.west@example.com', 26, 'Miami'),
    ('Jack Sparrow', 'jack.sparrow@example.com', 42, 'Raleigh'),
    ('Kate Winslet', 'kate.winslet@example.com', 39, 'Omaha'),
    ('Leo DiCaprio', 'leo.dicaprio@example.com', 41, 'Cleveland'),
    ('Monica Geller', 'monica.geller@example.com', 37, 'Tulsa'),
    ('Natalie Portman', 'natalie.portman@example.com', 36, 'Oakland'),
    ('Oliver Queen', 'oliver.queen@example.com', 34, 'Minneapolis'),
    ('Phoebe Buffay', 'phoebe.buffay@example.com', 32, 'Wichita'),
    ('Quentin Tarantino', 'quentin.tarantino@example.com', 53, 'Arlington'),
    ('Rose Tyler', 'rose.tyler@example.com', 25, 'Tampa'),
    ('Steve Rogers', 'steve.rogers@example.com', 45, 'Aurora'),
    ('Tony Stark', 'tony.stark@example.com', 44, 'Anaheim'),
    ('Ursula Andress', 'ursula.andress@example.com', 49, 'Honolulu'),
    ('Vince Vaughn', 'vince.vaughn@example.com', 46, 'Riverside'),
    ('Will Smith', 'will.smith@example.com', 48, 'Corpus Christi'),
    ('Xena Warrior', 'xena.warrior@example.com', 31, 'Lexington'),
    ('Yvonne Strahovski', 'yvonne.strahovski@example.com', 35, 'Stockton'),
    ('Zoe Saldana', 'zoe.saldana@example.com', 38, 'Henderson'),
    ('Adam Driver', 'adam.driver@example.com', 37, 'Saint Paul'),
    ('Betty White', 'betty.white@example.com', 52, 'Cincinnati'),
    ('Chris Evans', 'chris.evans@example.com', 36, 'Pittsburgh'),
    ('Daisy Ridley', 'daisy.ridley@example.com', 27, 'Greensboro'),
    ('Ethan Hunt', 'ethan.hunt@example.com', 43, 'Newark'),
    ('Felicity Jones', 'felicity.jones@example.com', 33, 'Plano'),
    ('Gal Gadot', 'gal.gadot@example.com', 32, 'Lincoln'),
    ('Harrison Ford', 'harrison.ford@example.com', 56, 'Orlando'),
    ('Isla Fisher', 'isla.fisher@example.com', 40, 'Chula Vista'),
    ('James Bond', 'james.bond@example.com', 45, 'Irvine'),
    ('Keira Knightley', 'keira.knightley@example.com', 34, 'Laredo'),
    ('Liam Neeson', 'liam.neeson@example.com', 57, 'Durham'),
    ('Margot Robbie', 'margot.robbie@example.com', 29, 'Chandler'),
    ('Natasha Romanoff', 'natasha.romanoff@example.com', 35, 'Madison'),
    ('Owen Wilson', 'owen.wilson@example.com', 47, 'Lubbock'),
    ('Penelope Cruz', 'penelope.cruz@example.com', 42, 'Winston'),
    ('Quinn Fabray', 'quinn.fabray@example.com', 24, 'Garland'),
    ('Ryan Reynolds', 'ryan.reynolds@example.com', 40, 'Glendale'),
    ('Scarlett Johansson', 'scarlett.johansson@example.com', 33, 'Hialeah'),
    ('Tom Cruise', 'tom.cruise@example.com', 54, 'Reno'),
    ('Vin Diesel', 'vin.diesel@example.com', 49, 'Chesapeake'),
    ('Wade Wilson', 'wade.wilson@example.com', 38, 'Gilbert'),
    ('Xander Harris', 'xander.harris@example.com', 30, 'Baton Rouge'),
    ('Ygritte Snow', 'ygritte.snow@example.com', 28, 'Irving'),
    ('Zack Snyder', 'zack.snyder@example.com', 51, 'Scottsdale'),
    ('Angelina Jolie', 'angelina.jolie@example.com', 41, 'Norfolk'),
    ('Brad Pitt', 'brad.pitt@example.com', 52, 'Fremont'),
    ('Cate Blanchett', 'cate.blanchett@example.com', 46, 'Boise'),
    ('Denzel Washington', 'denzel.washington@example.com', 58, 'Richmond'),
    ('Emily Blunt', 'emily.blunt@example.com', 35, 'Spokane'),
    ('Forest Whitaker', 'forest.whitaker@example.com', 55, 'Des Moines'),
    ('Gwyneth Paltrow', 'gwyneth.paltrow@example.com', 44, 'Tacoma'),
    ('Hugh Jackman', 'hugh.jackman@example.com', 48, 'Fontana'),
    ('Idris Elba', 'idris.elba@example.com', 46, 'San Bernardino'),
    ('Jennifer Lawrence', 'jennifer.lawrence@example.com', 30, 'Modesto'),
    ('Keanu Reeves', 'keanu.reeves@example.com', 53, 'Birmingham'),
    ('Lucy Liu', 'lucy.liu@example.com', 47, 'Rochester'),
    ('Matt Damon', 'matt.damon@example.com', 46, 'Oxnard'),
    ('Nicole Kidman', 'nicole.kidman@example.com', 49, 'Fayetteville'),
    ('Orlando Bloom', 'orlando.bloom@example.com', 40, 'Moreno Valley'),
    ('Priyanka Chopra', 'priyanka.chopra@example.com', 36, 'Akron'),
    ('Robert Downey Jr', 'robert.downey@example.com', 51, 'Yonkers'),
    ('Sandra Bullock', 'sandra.bullock@example.com', 52, 'Augusta'),
    ('Tom Hanks', 'tom.hanks@example.com', 59, 'Little Rock'),
    ('Viola Davis', 'viola.davis@example.com', 50, 'Amarillo'),
    ('Wesley Snipes', 'wesley.snipes@example.com', 54, 'Mobile'),
    ('Zendaya Coleman', 'zendaya.coleman@example.com', 23, 'Grand Prairie');

-- Verify data
SELECT COUNT(*) as total_records FROM benchmark_data;
